### ISSUE TITLE
sap_vm_provision: Add no_log:true to tasks with AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_infrastructure#1]
@sean-freeman  There are multiple task files that are consuming AWS Credentials as input variables/environment, which are visible when running -vvv debug. Please add no_log:true to all of them.

https://github.com/sap-linuxlab/community.sap_infrastructure/blob/main/roles/sap_vm_provision/tasks/platform_ansible/aws_ec2_vs/execute_main.yml

https://github.com/sap-linuxlab/community.sap_infrastructure/blob/main/roles/sap_vm_provision/tasks/platform_ansible_to_terraform/aws_ec2_vs/execute_main.yml

**Comment by sean-freeman** [comment]
Closed by PR #4 merge
