### ISSUE TITLE
sap_vm_provision: Hard dependency on AP4S

### ISSUE THREAD

**Issue by marcelmamula** [sap-linuxlab/community.sap_infrastructure#5]
@sean-freeman sap_vm_provision role is currently directly linked with AP4S and it cannot be executed separately.

common/set_ansible_vars.yml requires all AP4S variables to not fail set_facts, but they are not documented anywhere as requirement.

Proposal:
1. Uncouple both repositories by giving optional variable that would allow to use this role separately.
2. Update Readme to say it cannot run without AP4S https://github.com/sap-linuxlab/community.sap_infrastructure/blob/a67f6b81e4e947a66d832c143554a76e2ef3a123/roles/sap_vm_provision/README.md?plain=1#L7

**Comment by sean-freeman** [comment]
Closed by PR #6
